---
# vim: foldmarker=[[[,]]]:foldmethod=marker

- include: 'system_package_management.yml'
  tags: [ 'role::owncloud:pkg' ]

- name: Create ownCloud enforce permissions script
  template:
    src: 'usr/local/lib/owncloud-enforce-permissions.j2'
    dest: '{{ owncloud__enforce_permissions_script }}'
    owner: 'root'
    group: 'root'
    mode: '0744'
  tags: [ 'role::owncloud:base_install' ]
  register: permissions_script

- name: Run enforce permissions script
  command: '{{ owncloud__enforce_permissions_script }}'
  when: permissions_script.changed

- name: Include www-data to owncloud_group
  user:
    name: www-data
    append: yes
    groups: "{{ owncloud_group }}"

- include: 'configure_owncloud.yml'
  tags: [ 'role::owncloud:configure' ]

- include: 'setup_owncloud.yml'
  tags: [ 'role::owncloud:config' ]

- include: 'ldap.yml'
  when: (owncloud__ldap_enabled | bool)
  tags: [ 'role::owncloud:ldap' ]

- include: 'theme.yml'
  tags: [ 'role::owncloud:theme' ]

- include: 'copy.yml'
  tags: [ 'role::owncloud:copy' ]
